pipeline {
    agent none
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
	    agent {
        	docker {
                image 'node:6-alpine'
                args '-p 3000:8000'
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            agent {
        	docker {
                image 'node:6-alpine'
                args '-p 3000:8000'
                }
            }
	    steps {
		sh 'chmod 777 ./jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'
            }
        }
	stage('Document') {
	    agent any
	    steps {
		sh 'cd /home/dev/web'
		sh './node_modules/.bin/esdoc'
	    }
	}
        stage('Deliver') {
            agent any
            steps {
                    sh 'cd /home/dev/web'
		    sh 'sudo service mongod start'
                    sh 'chmod 777 ./jenkins/scripts/kill.sh'
                    sh 'chmod 777 ./jenkins/scripts/deliver.sh'
                    sh './jenkins/scripts/deliver.sh'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    sh './jenkins/scripts/kill.sh'            
            }
        }
    }
}

